name: bday
description: Happy BDay

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  provider: ^4.1.2
  google_fonts: ^1.1.0
  simple_animations: ^2.2.1
  get_it: ^4.0.2
  floor: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.12.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/images/cake.png
    - assets/images/flame01.png
    - assets/images/flame02.png
    - assets/images/flame03.png
    - assets/images/earth.png
    - assets/images/moon.png
    - assets/images/sun.png
