import 'dart:math';

import 'package:bday/extensions/extensions.dart';

class RandomPeople {
  static List<String> surnames = [
    "Garcia",
    "Rodriguez",
    "Gonzalez",
    "Fernandez",
    "Lopez",
    "Martinez",
    "Sanchez",
    "Perez",
    "Gomez",
    "Martin",
    "Jimenez",
    "Ruiz",
    "Hernandez",
    "Diaz",
    "Moreno",
    "Muñoz",
    "Alvarez",
    "Romero",
    "Alonso",
    "Gutierrez",
    "Navarro",
    "Torres",
    "Dominguez",
    "Vazquez",
    "Ramos",
    "Gil",
    "Ramirez",
    "Serrano",
    "Blanco",
    "Molina",
    "Morales",
    "Suarez",
    "Ortega",
    "Delgado",
    "Castro",
    "Ortiz",
    "Rubio",
    "Marin",
    "Sanz",
    "Nuñez",
    "Iglesias",
    "Medina",
    "Cortes",
    "Garrido",
    "Castillo",
    "Santos",
    "Lozano",
    "Guerrero",
    "Cano",
    "Prieto",
    "Mendez",
    "Cruz",
    "Calvo",
    "Herrera",
    "Gallego",
    "Flores",
    "Marquez",
    "Leon",
    "Peña",
    "Vidal",
    "Cabrera",
    "Campos",
    "Vega",
    "Fuentes",
    "Carrasco",
    "Diez",
    "Reyes",
    "Caballero",
    "Nieto",
    "Aguilar",
    "Santana",
    "Pascual",
    "Herrero",
    "Montero",
    "Hidalgo",
    "Lorenzo",
    "Gimenez",
    "Ibañez",
    "Ferrer",
    "Santiago",
    "Duran",
    "Vargas",
    "Benitez",
    "Mora",
    "Arias",
    "Vicente",
    "Carmona",
    "Crespo",
    "Roman",
    "Soto",
    "Pastor",
    "Saez",
    "Velasco",
    "Moya",
    "Soler",
    "Parra",
    "Rojas",
    "Esteban",
    "Bravo",
    "Gallardo"
  ];
  static List<String> namesM = [
    "Antonio",
    "Jose",
    "Manuel",
    "Francisco",
    "David",
    "Juan",
    "Jose Antonio",
    "Javier",
    "Daniel",
    "Jose Luis",
    "Francisco Javier",
    "Carlos",
    "Jesus",
    "Alejandro",
    "Miguel",
    "Jose Manuel",
    "Rafael",
    "Miguel Angel",
    "Pedro",
    "Angel",
    "Pablo",
    "Jose Maria",
    "Sergio",
    "Fernando",
    "Luis",
    "Jorge",
    "Alberto",
    "Juan Carlos",
    "Alvaro",
    "Juan Jose",
    "Adrian",
    "Diego",
    "Raul",
    "Juan Antonio",
    "Ivan",
    "Enrique",
    "Ruben",
    "Ramon",
    "Oscar",
    "Vicente",
    "Andres",
    "Juan Manuel",
    "Joaquin",
    "Santiago",
    "Eduardo",
    "Victor",
    "Mario",
    "Roberto",
    "Jaime",
    "Francisco Jose",
    "Marcos",
    "Ignacio",
    "Alfonso",
    "Jordi",
    "Ricardo",
    "Salvador",
    "Hugo",
    "Emilio",
    "Guillermo",
    "Gabriel",
    "Marc",
    "Julio",
    "Julian",
    "Gonzalo",
    "Jose Miguel",
    "Tomas",
    "Mohamed",
    "Agustin",
    "Martin",
    "Jose Ramon",
    "Nicolas",
    "Felix",
    "Joan",
    "Ismael",
    "Cristian",
    "Samuel",
    "Aitor",
    "Hector",
    "Juan Francisco",
    "Josep",
    "Mariano",
    "Lucas",
    "Jose Carlos",
    "Iker",
    "Domingo",
    "Sebastian",
    "Alfredo",
    "Alex",
    "Cesar",
    "Felipe",
    "Jose Angel",
    "Jose Ignacio",
    "Victor Manuel",
    "Rodrigo",
    "Luis Miguel",
    "Jose Francisco",
    "Juan Luis",
    "Gregorio",
    "Xavier",
    "Albert"
  ];

  static List<String> namesW = [
    "Maria Carmen",
    "Maria",
    "Carmen",
    "Josefa",
    "Ana Maria",
    "Isabel",
    "Maria Pilar",
    "Maria Dolores",
    "Laura",
    "Maria Teresa",
    "Ana",
    "Cristina",
    "Maria Angeles",
    "Marta",
    "Francisca",
    "Antonia",
    "Maria Isabel",
    "Maria Jose",
    "Lucia",
    "Dolores",
    "Sara",
    "Paula",
    "Elena",
    "Maria Luisa",
    "Pilar",
    "Raquel",
    "Rosa Maria",
    "Concepcion",
    "Manuela",
    "Mercedes",
    "Maria Jesus",
    "Beatriz",
    "Julia",
    "Rosario",
    "Nuria",
    "Juana",
    "Silvia",
    "Teresa",
    "Encarnacion",
    "Irene",
    "Alba",
    "Patricia",
    "Montserrat",
    "Andrea",
    "Rocio",
    "Rosa",
    "Monica",
    "Alicia",
    "Maria del Mar",
    "Angela",
    "Sonia",
    "Sandra",
    "Marina",
    "Susana",
    "Natalia",
    "Yolanda",
    "Margarita",
    "Maria Josefa",
    "Claudia",
    "Eva",
    "Maria Rosario",
    "Inmaculada",
    "Maria Mercedes",
    "Ana Isabel",
    "Esther",
    "Carla",
    "Sofia",
    "Noelia",
    "Veronica",
    "Angeles",
    "Nerea",
    "Carolina",
    "Maria Victoria",
    "Eva Maria",
    "Maria Rosa",
    "Miriam",
    "Ines",
    "Lorena",
    "Amparo",
    "Ana Belen",
    "Maria Concepcion",
    "Maria Elena",
    "Victoria",
    "Daniela",
    "Maria Antonia",
    "Catalina",
    "Lidia",
    "Consuelo",
    "Maria Nieves",
    "Celia",
    "Alejandra",
    "Martina",
    "Olga",
    "Gloria",
    "Emilia",
    "Ainhoa",
    "Luisa",
    "Fatima",
    "Maria Soledad",
    "Aurora"
  ];

  static List<String> names = namesM + namesW;

  static String name() {
    return (names..shuffle()).first;
  }

  static String surname() {
    return (surnames..shuffle()).first;
  }

  static DateTime birthday() {
    var age = Duration(days: Random().nextInt(37000));
    var today = DateUtils.today();
    return today.subtract(age);
  }
}
